const app=document.querySelector('#app'),cfg=window.HORIZON_CONFIG;
let client=null,step=0,device=localStorage.horizonDevice||'Horizon',currentUser=null,currentTab='home',online=true,profileMenu=false,activeProfileId=localStorage.horizonActiveProfile||'',storeQuery='',searchCache=[],installedState=[];
try{client=supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey)}catch(e){}
const icons={home:'⌂',library:'▣',store:'▤',social:'♙',settings:'⚙',power:'⏻'},labels={home:'Home',library:'Library',store:'Store',social:'Players',settings:'Settings',power:'Power'};
const catalog=[
 {id:'steam-cs2',name:'Counter-Strike 2',genre:'TACTICAL SHOOTER',art:'CS2',publisher:'Valve',desc:'A competitive tactical shooter. Free to play through Steam.'},
 {id:'steam-dota2',name:'Dota 2',genre:'MOBA',art:'D2',publisher:'Valve',desc:'Choose from more than a hundred heroes. Free to play through Steam.'},
 {id:'steam-tf2',name:'Team Fortress 2',genre:'TEAM SHOOTER',art:'TF2',publisher:'Valve',desc:'A class-based multiplayer action game. Free to play through Steam.'},
 {id:'steam-warframe',name:'Warframe',genre:'ONLINE ACTION',art:'WF',publisher:'Digital Extremes',desc:'Fast cooperative action across an evolving universe. Free to play through Steam.'},
 {id:'steam-brawlhalla',name:'Brawlhalla',genre:'PLATFORM FIGHTER',art:'BH',publisher:'Ubisoft',desc:'An online and local platform fighter. Free to play through Steam.'},
 {id:'steam-apex',name:'Apex Legends',genre:'BATTLE ROYALE',art:'AL',publisher:'Electronic Arts',desc:'A squad-based hero shooter. Free to play through Steam.'},
 {id:'steam-halo-infinite',name:'Halo Infinite',genre:'ARENA SHOOTER',art:'HI',publisher:'Xbox Game Studios',desc:'Free-to-play Halo multiplayer through Steam.'},
 {id:'steam-destiny2',name:'Destiny 2',genre:'ONLINE SHOOTER',art:'D2',publisher:'Bungie',desc:'A shared-world action shooter. Free base game through Steam.'}
];
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function accountName(){return currentUser?.user_metadata?.display_name||currentUser?.email?.split('@')[0]||'Player'}
function loadProfiles(){let p=[];try{p=JSON.parse(localStorage.horizonProfiles||'[]')}catch{}if(!p.length){p=[{id:'p1',name:accountName(),tagline:'Ready to play',avatar:'PL',color:0}];saveProfiles(p)}if(!activeProfileId||!p.some(x=>x.id===activeProfileId)){activeProfileId=p[0].id;localStorage.horizonActiveProfile=activeProfileId}return p}
function saveProfiles(p){localStorage.horizonProfiles=JSON.stringify(p)}function profile(){return loadProfiles().find(x=>x.id===activeProfileId)||loadProfiles()[0]}function name(){return profile().name}
function avatar(p,big=false){let g=[['#35a4ff','#8055ff'],['#ff668e','#8c4dff'],['#37d3b0','#2478ff']][p.color||0];return `<div class="avatar" style="${big?'width:72px;height:72px;font-size:22px;':''}background:linear-gradient(135deg,${g[0]},${g[1]})">${esc(p.avatar||p.name.slice(0,2).toUpperCase())}</div>`}
function sound(type='move'){if(localStorage.horizonSounds==='0')return;try{let a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=type==='select'?720:440;g.gain.setValueAtTime(.03,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.075);o.start();o.stop(a.currentTime+.08)}catch{}}
function toast(t){let e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function menu(){if(!profileMenu)return'';let ps=loadProfiles();return `<div class="profile-menu" onclick="event.stopPropagation()"><h4>CHOOSE PROFILE</h4>${ps.map(p=>`<div class="profile-choice ${p.id===activeProfileId?'active':''}" onclick="switchProfile('${p.id}')">${avatar(p)}<div class="profile-copy"><b>${esc(p.name)}</b><small>${esc(p.tagline)}</small></div>${p.id===activeProfileId?'✓':''}</div>`).join('')}<button class="menu-action" onclick="openProfiles()">⚙ Manage profiles <span style="float:right">${ps.length}/3</span></button><button class="menu-action" onclick="openLogin()">＋ Sign in to another account</button><button class="menu-action danger" onclick="logout()">↪ Sign out</button></div>`}
function header(section){let p=profile();return `<div class="header"><div class="brand"><div class="logo">H</div><div>HORIZON<small>${section.toUpperCase()}</small></div></div><div class="right-status"><span class="online">● ${online?'ONLINE':'OFFLINE'}</span><span class="clock">${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><div class="profile-wrap"><div class="profile-pill" onclick="event.stopPropagation();profileMenu=!profileMenu;render()">${avatar(p)}${esc(p.name)}⌄</div>${menu()}</div></div></div>`}
function dock(){return `<div class="dock">${Object.keys(labels).map(k=>`<div class="nav-item ${currentTab===k?'active':''}" onclick="nav('${k}')"><span>${icons[k]}</span><b>${labels[k]}</b></div>`).join('')}</div><div class="hint">A / CLICK SELECT &nbsp;&nbsp; B / ESC BACK &nbsp;&nbsp; ← → NAVIGATE</div>`}
function shell(content,section=currentTab){return `<div class="screen">${header(section)}<main class="content">${content}</main>${dock()}</div>`}
const setupSteps=()=>`<div class="setup-steps">${[0,1,2,3].map(x=>`<span class="${x<=step?'on':''}"></span>`).join('')}</div>`;
function setup(){let c;if(step===0)c=`${setupSteps()}<p class="eyebrow">WELCOME</p><h1>Meet Horizon Desktop.</h1><p class="muted">A smooth, private desktop for files, the web, games and everyday work.</p><button onclick="step=1;setup()">GET STARTED</button>`;if(step===1)c=`${setupSteps()}<p class="eyebrow">YOUR DEVICE</p><h1>Name this Horizon.</h1><input id="device" value="Horizon"><button onclick="device=document.querySelector('#device').value||'Horizon';step=2;setup()">CONTINUE</button>`;if(step===2)c=`${setupSteps()}<p class="eyebrow">HORIZON NETWORK</p><h1>Connect—or stay local.</h1><p class="muted">An online account is optional. Create one at:</p><p class="url">${cfg.accountUrl}</p><button onclick="step=3;setup()">CONNECT ACCOUNT</button><button class="ghost" onclick="finishOffline()">USE WITHOUT ACCOUNT</button>`;if(step===3)c=`${setupSteps()}<p class="eyebrow">SIGN IN</p><h1>Welcome back.</h1>${loginFields()}<button onclick="login(false)">SIGN IN & FINISH</button><button class="ghost" onclick="finishOffline()">SKIP FOR NOW</button>`;app.innerHTML=`<div class="screen">${header('Setup')}<div class="center card setup-card">${c}</div></div>`}
function loginFields(){return `<input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><p id="error" class="muted"></p>`}
async function login(addAccount=true){let email=document.querySelector('#email').value,password=document.querySelector('#password').value,err=document.querySelector('#error');if(!client){err.textContent='Horizon Network is not configured.';return}let {data,error}=await client.auth.signInWithPassword({email,password});if(error){err.textContent=error.message;return}currentUser=data.user;localStorage.horizonSession=JSON.stringify(data.session);localStorage.horizonSetup='1';let ps=loadProfiles();if(addAccount&&!ps.some(p=>p.accountId===data.user.id)){if(ps.length>=3){err.textContent='This device already has the maximum of 3 profiles.';return}let nm=accountName(),np={id:'p'+Date.now(),accountId:data.user.id,name:nm,tagline:'Horizon Network',avatar:nm.slice(0,2).toUpperCase(),color:ps.length};ps.push(np);saveProfiles(ps);activeProfileId=np.id;localStorage.horizonActiveProfile=np.id}await saveDeviceRemote();closeModal();nav('home')}
async function finishOffline(){localStorage.horizonSetup='1';loadProfiles();await saveDeviceRemote();toast('Horizon Desktop is ready')}
async function logout(){if(client)await client.auth.signOut();localStorage.removeItem('horizonSession');currentUser=null;profileMenu=false;openLogin(true)}
function activateProfile(id){activeProfileId=id;localStorage.horizonActiveProfile=id;profileMenu=false;render();toast(`Switched to ${name()}`)}
function switchProfile(id){let p=loadProfiles().find(x=>x.id===id);if(!p||id===activeProfileId){profileMenu=false;render();return}if(p.lockedUntil>Date.now()){toast(`Profile locked for ${Math.ceil((p.lockedUntil-Date.now())/60000)} more minutes`);return}if(p.pinHash){profileMenu=false;requestPin(id);return}activateProfile(id)}
function nav(tab){profileMenu=false;sound();if(tab==='power'){openPower();return}currentTab=tab;render()}
function installedIds(){return installedState}function installed(){return catalog.filter(g=>installedState.includes(g.id))}async function loadInstalled(){try{let d=await(await fetch('/api/apps')).json();installedState=d.installed||[]}catch{installedState=[]}}
function render(){let count=installed().filter(g=>g.id!=='steam').length,body;if(currentTab==='home')body=`<div class="hero"><section class="feature"><p class="eyebrow">${count?'YOUR STEAM LIBRARY':'WELCOME TO HORIZON STORE'}</p><h2>${count?`Ready to play, ${esc(name())}?`:'Steam games. Horizon style.'}</h2><p>${count?'Choose an installed Steam game from your Horizon Library.':'Nothing is preinstalled. Pick a free Steam game and Steam will handle its official licence and download.'}</p><div class="feature-actions"><button onclick="nav('${count?'library':'store'}')">${count?'OPEN LIBRARY':'DISCOVER GAMES'}</button><button class="ghost" onclick="nav('store')">OPEN STORE</button></div></section><aside class="side-stack"><div class="stat-card"><p class="eyebrow">STEAM LIBRARY</p><strong>${count} GAMES</strong><span class="muted">Detected from your Steam installation</span></div><div class="stat-card"><p class="eyebrow">HORIZON + STEAM</p><strong>OFFICIAL</strong><span class="muted">Steam controls licences, downloads and updates</span><div class="progress"><b style="width:${count?42:8}%"></b></div></div></aside></div>`;if(currentTab==='library')body=libraryPage();if(currentTab==='store')body=storePage();if(currentTab==='social')body=socialPage();if(currentTab==='settings')body=settingsPage();app.innerHTML=shell(body)}
function libraryPage(){let gs=installed().filter(g=>g.id!=='steam');return `<div class="section-title"><div><p class="eyebrow">YOUR STEAM COLLECTION</p><h1>Library</h1></div><span class="muted">${gs.length} Steam games installed</span></div><div class="tiles">${gs.map(g=>`<div class="tile" onclick="gameDetails('${g.id}')"><span class="symbol">${g.art}</span><p class="eyebrow">${g.genre}</p><h2>${g.name}</h2><b>VIEW GAME</b></div>`).join('')}<div class="tile" onclick="nav('store')"><span class="symbol">＋</span><p class="eyebrow">HORIZON STORE</p><h2>Discover Steam games</h2><b>OPEN STORE</b></div></div>`}
function storePage(){let q=storeQuery.toLowerCase(),gs=catalog.filter(g=>(g.name+' '+g.genre+' '+g.publisher).toLowerCase().includes(q));return `<div class="section-title"><div><p class="eyebrow">HORIZON STORE • POWERED BY STEAM</p><h1>Free Steam games</h1></div><input style="width:320px;margin:0" value="${esc(storeQuery)}" oninput="storeQuery=this.value;render()" placeholder="Search Steam games..."></div><div class="store-grid">${gs.map(g=>`<div class="store-card" onclick="gameDetails('${g.id}')"><div class="store-art">${g.art}</div><span class="badge">${installedIds().includes(g.id)?'INSTALLED':g.id==='steam'?'PLATFORM':'FREE ON STEAM'}</span><p class="eyebrow">${g.genre}</p><h2>${g.name}</h2><span class="muted">${g.desc}</span></div>`).join('')}</div>`}
function gameDetails(id){let g=catalog.find(x=>x.id===id),inside=installedIds().includes(id);modal(`<div class="detail-hero"><strong>${g.art}</strong></div><p class="eyebrow">${g.genre} • ${g.publisher}</p><h2>${g.name}</h2><p class="muted">${g.desc}</p><div class="device-grid"><div class="device-stat"><b>Steam account required</b><span>Sign in securely inside the official Steam client</span></div><div class="device-stat"><b>Free Steam licence</b><span>Steam handles ownership, download and updates</span></div></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">CLOSE</button>${inside?`<button class="ghost" onclick="uninstallGame('${id}')">UNINSTALL</button><button onclick="closeModal();play('${id}')">OPEN</button>`:`<button onclick="installGame('${id}')">INSTALL WITH STEAM</button>`}</div>`)}
async function installGame(id){let g=catalog.find(x=>x.id===id);modal(`<p class="eyebrow">HORIZON STORE • STEAM</p><h2>Opening ${g.name}</h2><p class="muted">Horizon is preparing the official Steam client. Steam will confirm the licence, storage location and download.</p><div class="progress"><b style="width:70%;animation:drift 2s infinite alternate"></b></div>`);try{let r=await fetch('/api/apps/install',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({app:id})}),d=await r.json();if(!r.ok)throw Error(d.error||'Installation failed');await loadInstalled();closeModal();render();toast(d.installingViaSteam?`Continue installation in Steam`:`${g.name} installed`)}catch(e){modal(`<p class="eyebrow">INSTALLATION FAILED</p><h2>Could not open ${g.name}</h2><p class="muted">${esc(e.message)}</p><div class="modal-actions"><button onclick="closeModal()">CLOSE</button></div>`)}}
async function uninstallGame(id){let g=catalog.find(x=>x.id===id);modal(`<p class="eyebrow">HORIZON STORE</p><h2>Removing ${g.name}</h2><p class="muted">Please wait…</p>`);try{await fetch('/api/apps/uninstall',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({app:id})});await loadInstalled();closeModal();render();toast(`${g.name} uninstalled`)}catch(e){closeModal();toast('Uninstall failed')}}
function socialPage(){let p=profile(),friends=getFriends();return `<div class="section-title"><div><p class="eyebrow">HORIZON NETWORK</p><h1>Players</h1></div><button onclick="online=!online;render()">GO ${online?'OFFLINE':'ONLINE'}</button></div><div class="social-grid"><div class="panel"><p class="eyebrow">YOUR PROFILE</p><div style="display:flex;align-items:center;gap:18px;margin:20px 0">${avatar(p,true)}<div><h2 style="margin:0">${esc(p.name)}</h2><span class="muted">${esc(p.tagline)} • 4 achievements</span></div></div><button onclick="editProfile('${p.id}')">CUSTOMISE PROFILE</button><button class="ghost" onclick="createProfile()">ADD PROFILE (${loadProfiles().length}/3)</button>${friends.length?`<p class="eyebrow" style="margin-top:25px">FRIENDS</p><div class="friends-strip">${friends.map(f=>`<div class="friend-chip">${avatar(f)}${esc(f.name)}</div>`).join('')}</div>`:''}</div><div class="panel"><p class="eyebrow">FIND PLAYERS</p><h2>Connect with friends</h2><input id="player-search" placeholder="Search by Horizon name..." onkeydown="if(event.key==='Enter')searchPlayers()"><button onclick="searchPlayers()">SEARCH</button><div id="friend-results" class="friend-results"><div class="empty-state">Search for a Horizon player to see possible matches.</div></div></div></div>`}
function friendKey(){return 'horizonFriends_'+activeProfileId}function getFriends(){try{return JSON.parse(localStorage[friendKey()]||'[]')}catch{return[]}}function saveFriends(f){localStorage[friendKey()]=JSON.stringify(f)}
async function searchPlayers(){let q=document.querySelector('#player-search').value.trim(),box=document.querySelector('#friend-results');if(q.length<2){box.innerHTML='<div class="empty-state">Enter at least 2 characters.</div>';return}box.innerHTML='<div class="empty-state">Searching Horizon Network…</div>';let rows=[];if(client)try{let query=client.from('profiles').select('id,display_name,avatar_color,status').ilike('display_name',`%${q}%`).limit(8);if(currentUser?.id)query=query.neq('id',currentUser.id);let {data,error}=await query;if(!error&&data)rows=data.map((x,i)=>({id:x.id,name:x.display_name,avatar:(x.display_name||'PL').slice(0,2).toUpperCase(),color:x.avatar_color||i%3,tagline:x.status||'Horizon player'}))}catch{}searchCache=rows;if(!rows.length){box.innerHTML='<div class="empty-state">No matching Horizon accounts found.</div>';return}let f=getFriends();box.innerHTML=rows.map((r,i)=>`<div class="friend-result">${avatar(r)}<div class="profile-copy"><b>${esc(r.name)}</b><small>${esc(r.tagline)}</small></div><button class="${f.some(x=>x.id===r.id)?'sent':''}" onclick="addFriend(${i},this)">${f.some(x=>x.id===r.id)?'REQUEST SENT':'ADD FRIEND'}</button></div>`).join('')}
async function addFriend(i,b){let r=searchCache[i],f=getFriends();if(client&&currentUser?.id){let {error}=await client.from('friend_requests').insert({sender_id:currentUser.id,receiver_id:r.id});if(error&&error.code!=='23505'){toast('Could not send request: '+error.message);return}}if(!f.some(x=>x.id===r.id)){f.push(r);saveFriends(f)}b.textContent='REQUEST SENT';b.classList.add('sent');b.disabled=true;toast(`Friend request sent to ${r.name}`)}
function createProfile(){let ps=loadProfiles();if(ps.length>=3){toast('You can only have 3 profiles');return}let p={id:'p'+Date.now(),name:`Player ${ps.length+1}`,tagline:'New Horizon player',avatar:`P${ps.length+1}`,color:ps.length};ps.push(p);saveProfiles(ps);activeProfileId=p.id;localStorage.horizonActiveProfile=p.id;editProfile(p.id,true)}
function editProfile(id,isNew=false){let p=loadProfiles().find(x=>x.id===id);modal(`<p class="eyebrow">${isNew?'NEW PROFILE':'PROFILE CUSTOMISATION'}</p><h2>${isNew?'Create your player':'Make it yours'}</h2><label>Display name</label><input id="profile-name" value="${esc(p.name)}" maxlength="20"><label>Profile message</label><input id="profile-tagline" value="${esc(p.tagline)}" maxlength="40"><label>Avatar colour</label><div class="avatar-grid">${[0,1,2].map(i=>`<div data-color="${i}" class="avatar-option ${p.color===i?'selected':''}" style="background:linear-gradient(135deg,${['#35a4ff','#ff668e','#37d3b0'][i]},${['#8055ff','#8c4dff','#2478ff'][i]})" onclick="document.querySelectorAll('.avatar-option').forEach(x=>x.classList.remove('selected'));this.classList.add('selected')">${esc(p.avatar)}</div>`).join('')}</div><div class="modal-actions">${loadProfiles().length>1?`<button class="ghost" onclick="deleteProfile('${id}')">DELETE</button>`:''}<button class="ghost" onclick="closeModal()">CANCEL</button><button onclick="saveProfile('${id}')">SAVE PROFILE</button></div>`)}
function saveProfile(id){let ps=loadProfiles(),p=ps.find(x=>x.id===id);p.name=document.querySelector('#profile-name').value.trim()||p.name;p.tagline=document.querySelector('#profile-tagline').value.trim()||'Horizon player';p.color=Number(document.querySelector('.avatar-option.selected')?.dataset.color||0);p.avatar=p.name.slice(0,2).toUpperCase();saveProfiles(ps);closeModal();render();toast('Profile saved')}
function deleteProfile(id){let ps=loadProfiles();if(ps.length<2)return;ps=ps.filter(x=>x.id!==id);saveProfiles(ps);activeProfileId=ps[0].id;localStorage.horizonActiveProfile=activeProfileId;closeModal();render();toast('Profile removed')}
function openProfiles(){profileMenu=false;let ps=loadProfiles();modal(`<p class="eyebrow">SHARED DEVICE</p><h2>Profiles (${ps.length}/3)</h2><p class="muted">Each profile has its own friend list and optional PIN.</p><div class="profile-list">${ps.map(p=>`<div class="profile-row">${avatar(p)}<div class="profile-copy"><b>${esc(p.name)}</b><small>${p.pinHash?'🔒 ':''}${esc(p.tagline)}</small></div><button class="ghost" onclick="closeModal();switchProfile('${p.id}')">USE</button><button onclick="editProfile('${p.id}')">EDIT</button></div>`).join('')}</div><div class="modal-actions"><button class="ghost" onclick="closeModal()">DONE</button><button onclick="createProfile()" ${ps.length>=3?'disabled':''}>ADD PROFILE</button></div>`)}
function openLogin(signedOut=false){profileMenu=false;modal(`<p class="eyebrow">HORIZON ACCOUNT</p><h2>${signedOut?'Signed out':'Sign in to another account'}</h2><p class="muted">Connect a Horizon Network account to this shared device.</p>${loginFields()}<div class="modal-actions"><button class="ghost" onclick="closeModal()">CANCEL</button><button onclick="login(true)">SIGN IN</button></div>`)}
async function hashPin(pin){let bytes=new TextEncoder().encode('horizon-profile-pin:'+pin),hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function requestPin(id){let p=loadProfiles().find(x=>x.id===id),remaining=6-(p.failedAttempts||0);modal(`<p class="eyebrow">LOCKED PROFILE</p><h2>Enter ${esc(p.name)}'s PIN</h2><p class="muted">${remaining} attempts remaining before a 15-minute lock.</p><input id="unlock-pin" type="password" inputmode="numeric" maxlength="8" placeholder="4–8 digit PIN" onkeydown="if(event.key==='Enter')verifyPin('${id}')"><p id="pin-error" class="muted"></p><div class="modal-actions"><button class="ghost" onclick="closeModal()">CANCEL</button><button onclick="verifyPin('${id}')">UNLOCK</button></div>`)}
async function verifyPin(id){let ps=loadProfiles(),p=ps.find(x=>x.id===id),input=document.querySelector('#unlock-pin').value;if(await hashPin(input)===p.pinHash){p.failedAttempts=0;p.lockedUntil=0;saveProfiles(ps);closeModal();activateProfile(id);return}p.failedAttempts=(p.failedAttempts||0)+1;if(p.failedAttempts>=6){p.failedAttempts=0;p.lockedUntil=Date.now()+15*60*1000;saveProfiles(ps);closeModal();toast('Too many attempts. Profile locked for 15 minutes.');return}saveProfiles(ps);document.querySelector('#pin-error').textContent=`Incorrect PIN. ${6-p.failedAttempts} attempts remaining.`;document.querySelector('#unlock-pin').value=''}
function managePin(){let has=!!profile().pinHash;modal(`<p class="eyebrow">PROFILE SECURITY</p><h2>${has?'Change your PIN':'Add a profile PIN'}</h2><p class="muted">Use 4–8 digits. After 6 incorrect attempts, the profile locks for 15 minutes.</p><input id="new-pin" type="password" inputmode="numeric" maxlength="8" placeholder="New PIN"><input id="confirm-pin" type="password" inputmode="numeric" maxlength="8" placeholder="Confirm PIN"><p id="pin-error" class="muted"></p><div class="modal-actions">${has?'<button class="ghost" onclick="removePin()">REMOVE PIN</button>':''}<button class="ghost" onclick="closeModal()">CANCEL</button><button onclick="savePin()">SAVE PIN</button></div>`)}
async function savePin(){let pin=document.querySelector('#new-pin').value,confirm=document.querySelector('#confirm-pin').value,err=document.querySelector('#pin-error');if(!/^\d{4,8}$/.test(pin)){err.textContent='PIN must contain 4–8 numbers.';return}if(pin!==confirm){err.textContent='The PINs do not match.';return}let ps=loadProfiles(),p=ps.find(x=>x.id===activeProfileId);p.pinHash=await hashPin(pin);p.failedAttempts=0;p.lockedUntil=0;saveProfiles(ps);closeModal();render();toast('Profile PIN enabled')}
function removePin(){let ps=loadProfiles(),p=ps.find(x=>x.id===activeProfileId);delete p.pinHash;delete p.failedAttempts;delete p.lockedUntil;saveProfiles(ps);closeModal();render();toast('Profile PIN removed')}
function settingsPage(){let locked=!!profile().pinHash;return `<div class="section-title"><div><p class="eyebrow">SYSTEM</p><h1>Settings</h1></div><span class="muted">Horizon OS Preview 0.6</span></div><div class="settings-grid"><div class="row"><div><b>Profile PIN</b><div class="muted">${locked?'PIN protection enabled':'Protect this profile with 4–8 digits'}</div></div><button onclick="managePin()">${locked?'CHANGE PIN':'ADD PIN'}</button></div><div class="row"><div><b>UI sounds</b><div class="muted">Navigation audio</div></div><div class="toggle ${localStorage.horizonSounds==='0'?'':'on'}" onclick="this.classList.toggle('on');localStorage.horizonSounds=this.classList.contains('on')?'1':'0'"></div></div><div class="row"><div><b>Background motion</b><div class="muted">Animated atmosphere</div></div><div class="toggle on" onclick="this.classList.toggle('on');document.querySelector('.backdrop').style.display=this.classList.contains('on')?'block':'none'"></div></div><div class="row"><div><b>Controller support</b><div class="muted">PS4, PS5 and Xbox</div></div><span class="online">READY</span></div><div class="row"><div><b>System update</b><div class="muted">Preview channel</div></div><button onclick="toast('Horizon is up to date')">CHECK</button></div><div class="row"><div><b>Device</b><div class="muted">${esc(device)}</div></div><button onclick="manageDevice()">MANAGE DEVICE</button></div></div>`}
async function manageDevice(){let s={};try{s=await(await fetch('/api/system')).json()}catch{}modal(`<p class="eyebrow">DEVICE MANAGEMENT</p><h2>${esc(device)}</h2><div class="device-grid"><div class="device-stat"><b>Operating system</b><span>${esc(s.platform||'Horizon OS Preview 0.5')}</span></div><div class="device-stat"><b>Host name</b><span>${esc(s.hostname||'horizon-os')}</span></div><div class="device-stat"><b>Architecture</b><span>64-bit PC</span></div><div class="device-stat"><b>Update channel</b><span>Preview</span></div></div><label style="display:block;margin-top:20px">Device name</label><input id="device-name" value="${esc(device)}"><div class="modal-actions"><button class="ghost" onclick="openPower()">POWER OPTIONS</button><button class="ghost" onclick="closeModal()">CANCEL</button><button onclick="saveDevice()">SAVE</button></div>`)}
async function saveDevice(){device=document.querySelector('#device-name').value.trim()||device;localStorage.horizonDevice=device;await saveDeviceRemote();closeModal();render();toast('Device settings saved')}async function saveDeviceRemote(){try{await fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceName:device})})}catch{}}
function openPower(){profileMenu=false;modal(`<p class="eyebrow">POWER</p><h2>What would you like to do?</h2><p class="muted">Unsaved game progress may be lost.</p><div class="modal-actions"><button class="ghost" onclick="closeModal()">CANCEL</button><button class="ghost" onclick="systemAction('restart')">RESTART</button><button onclick="systemAction('poweroff')">POWER OFF</button></div>`)}async function systemAction(action){await fetch('/api/power',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})})}
function modal(html){closeModal();document.body.insertAdjacentHTML('beforeend',`<div id="modal" class="modal-shade" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`)}function closeModal(){document.querySelector('#modal')?.remove()}
async function play(id){sound('select');try{let r=await fetch('/api/apps/launch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({app:id})}),d=await r.json();if(!r.ok)throw Error(d.error||'Launch failed');toast(`Opening ${catalog.find(x=>x.id===id)?.name}`)}catch(e){toast(e.message)}}
document.addEventListener('click',()=>{if(profileMenu){profileMenu=false;render()}});window.addEventListener('keydown',e=>{if(document.querySelector('#modal')){if(e.key==='Escape')closeModal();return}if(e.key==='Escape'&&currentTab!=='home')nav('home')});
(async()=>{await loadInstalled();if(localStorage.horizonSetup==='1'&&localStorage.horizonSession){try{let s=JSON.parse(localStorage.horizonSession);currentUser=s.user;loadProfiles();render()}catch{setup()}}else setup()})();
