const app=document.querySelector('#app'),cfg=window.HORIZON_CONFIG;let client=null,step=0,device='Horizon',currentUser=null,currentTab='home',online=true;
try{client=supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey)}catch(e){}
const icons={home:'⌂',library:'▣',store:'▤',social:'♙',settings:'⚙',power:'⏻'};
const labels={home:'Home',library:'Library',store:'Store',social:'Players',settings:'Settings',power:'Power'};
function name(){return currentUser?.user_metadata?.display_name||currentUser?.email?.split('@')[0]||'Player'}
function sound(type='move'){try{let a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.type='sine';o.frequency.value=type==='select'?720:440;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.075);o.start();o.stop(a.currentTime+.08)}catch(e){}}
function toast(t){let e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function header(section){return `<div class="header"><div class="brand"><div class="logo">H</div><div>HORIZON<small>${section.toUpperCase()}</small></div></div><div class="right-status"><span class="online">● ${online?'ONLINE':'OFFLINE'}</span><span class="clock">${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><div class="profile-pill" onclick="nav('social')"><div class="avatar">${name().slice(0,2).toUpperCase()}</div>${name()}</div></div></div>`}
function dock(){return `<div class="dock">${Object.keys(labels).map(k=>`<div class="nav-item ${currentTab===k?'active':''}" onclick="nav('${k}')"><span>${icons[k]}</span><b>${labels[k]}</b></div>`).join('')}</div><div class="hint">A / CLICK SELECT &nbsp;&nbsp; B / ESC BACK &nbsp;&nbsp; ← → NAVIGATE</div>`}
function shell(content,section=currentTab){return `<div class="screen">${header(section)}<main class="content">${content}</main>${dock()}</div>`}
const steps=()=>`<div class="setup-steps">${[0,1,2,3].map(x=>`<span class="${x<=step?'on':''}"></span>`).join('')}</div>`;
function setup(){let c='';if(step===0)c=`${steps()}<p class="eyebrow">WELCOME</p><h1>Meet Horizon OS.</h1><p class="muted">A console-first home for games, profiles and Horizon Network.</p><button onclick="step=1;sound('select');setup()">GET STARTED</button>`;if(step===1)c=`${steps()}<p class="eyebrow">YOUR DEVICE</p><h1>Name this Horizon.</h1><input id="device" value="Horizon" maxlength="28"><button onclick="device=document.querySelector('#device').value||'Horizon';step=2;sound('select');setup()">CONTINUE</button>`;if(step===2)c=`${steps()}<p class="eyebrow">HORIZON ACCOUNT</p><h1>Connect your player.</h1><p class="muted">On another device, visit:</p><p class="url">${cfg.accountUrl}</p><p class="muted">Create your account there, then return here.</p><button onclick="step=3;sound('select');setup()">I'VE CREATED IT</button>`;if(step===3)c=`${steps()}<p class="eyebrow">SIGN IN</p><h1>Welcome back.</h1><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><p id="error" class="muted"></p><button onclick="login()">SIGN IN & FINISH</button>`;app.innerHTML=`<div class="screen">${header('Setup')}<div class="center card setup-card">${c}</div></div>`}
async function login(){let email=document.querySelector('#email').value,password=document.querySelector('#password').value;if(!client){document.querySelector('#error').textContent='Horizon Network is not configured.';return}let {data,error}=await client.auth.signInWithPassword({email,password});if(error){document.querySelector('#error').textContent=error.message;return}currentUser=data.user;localStorage.horizonSession=JSON.stringify(data.session);localStorage.horizonSetup='1';await fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceName:device})});sound('select');nav('home')}
function nav(tab){sound('move');if(tab==='power'){if(confirm('Power off Horizon OS?'))fetch('/api/power',{method:'POST'});return}currentTab=tab;render()}
function render(){let n=name(),body='';if(currentTab==='home')body=`<div class="hero"><section class="feature"><p class="eyebrow">YOUR NEXT ADVENTURE</p><h2>Ready to play, ${n}?</h2><p>Jump back into Neon Snake or discover something new in Horizon Store.</p><div class="feature-actions"><button onclick="play('snake')">PLAY NOW</button><button class="ghost" onclick="nav('store')">OPEN STORE</button></div></section><aside class="side-stack"><div class="stat-card"><p class="eyebrow">HORIZON LIBRARY</p><strong>2 GAMES</strong><span class="muted">Installed and ready to play</span></div><div class="stat-card"><p class="eyebrow">ACHIEVEMENTS</p><strong>4 / 24</strong><span class="muted">Keep playing to unlock rewards</span><div class="progress"><b></b></div></div></aside></div>`;
if(currentTab==='library')body=`<div class="section-title"><div><p class="eyebrow">YOUR COLLECTION</p><h1>Library</h1></div><span class="muted">2 games installed</span></div><div class="tiles"><div class="tile" onclick="play('orbit')"><span class="symbol">OD</span><p class="eyebrow">ARCADE</p><h2>Orbit Dash</h2><b>PLAY</b></div><div class="tile" onclick="play('snake')"><span class="symbol">NS</span><p class="eyebrow">CLASSIC</p><h2>Neon Snake</h2><b>PLAY</b></div><div class="tile" onclick="nav('store')"><span class="symbol">＋</span><p class="eyebrow">HORIZON STORE</p><h2>Discover games</h2><b>EXPLORE</b></div></div>`;
if(currentTab==='store')body=`<div class="section-title"><div><p class="eyebrow">HORIZON STORE</p><h1>Discover</h1></div><input style="width:300px;margin:0" placeholder="Search Horizon games..."></div><div class="tiles"><div class="tile"><span class="symbol">OD</span><p class="eyebrow">INSTALLED</p><h2>Orbit Dash</h2><b>IN LIBRARY</b></div><div class="tile"><span class="symbol">NS</span><p class="eyebrow">INSTALLED</p><h2>Neon Snake</h2><b>IN LIBRARY</b></div><div class="tile"><span class="symbol">HZ</span><p class="eyebrow">COMING SOON</p><h2>Skyline Racer</h2><b>FOLLOW</b></div><div class="tile"><span class="symbol">＋</span><p class="eyebrow">DEVELOPER HUB</p><h2>Publish a game</h2><b>LEARN MORE</b></div></div>`;
if(currentTab==='social')body=`<div class="section-title"><div><p class="eyebrow">HORIZON NETWORK</p><h1>Players</h1></div><button onclick="online=!online;toast(online?'You are online':'You appear offline');render()">GO ${online?'OFFLINE':'ONLINE'}</button></div><div class="social-grid"><div class="panel"><p class="eyebrow">YOUR PROFILE</p><div style="display:flex;align-items:center;gap:18px;margin:20px 0"><div class="avatar" style="width:72px;height:72px;font-size:22px">${n.slice(0,2).toUpperCase()}</div><div><h2 style="margin:0">${n}</h2><span class="muted">Horizon Level 1 • 4 achievements</span></div></div><button onclick="toast('Profile customisation opened')">CUSTOMISE PROFILE</button><button class="ghost" onclick="toast('New local profile ready')">ADD PROFILE</button></div><div class="panel"><p class="eyebrow">FIND PLAYERS</p><h2>Connect with friends</h2><input placeholder="Search by Horizon name..."><button onclick="toast('Player search sent')">SEARCH</button><p class="muted">Friends and requests will appear here when found.</p></div></div>`;
if(currentTab==='settings')body=`<div class="section-title"><div><p class="eyebrow">SYSTEM</p><h1>Settings</h1></div><span class="muted">Horizon OS Preview 0.4</span></div><div class="settings-grid"><div class="row"><div><b>UI sounds</b><div class="muted">Navigation and selection audio</div></div><div class="toggle on" onclick="this.classList.toggle('on');sound()"></div></div><div class="row"><div><b>Background motion</b><div class="muted">Animated Horizon atmosphere</div></div><div class="toggle on" onclick="this.classList.toggle('on')"></div></div><div class="row"><div><b>Controller support</b><div class="muted">PS4, PS5 and Xbox controllers</div></div><span class="online">READY</span></div><div class="row"><div><b>System update</b><div class="muted">You are on the latest preview</div></div><button onclick="toast('Horizon is up to date')">CHECK</button></div><div class="row"><div><b>Network</b><div class="muted">Automatic connection enabled</div></div><span class="online">CONNECTED</span></div><div class="row"><div><b>Device</b><div class="muted">${device}</div></div><button onclick="toast('Device settings opened')">MANAGE</button></div></div>`;app.innerHTML=shell(body)}
function play(id){sound('select');if(id==='snake')snake();else toast('Orbit Dash update is coming soon')}
function snake(){app.innerHTML=shell(`<div class="center card setup-card"><p class="eyebrow">NOW PLAYING</p><h1>Neon Snake</h1><p class="muted">Use arrow keys. Press Escape to return.</p><canvas id="game" width="600" height="360" style="background:#050812;width:100%;border-radius:16px"></canvas></div>`,'Neon Snake');let c=document.querySelector('#game'),x=c.getContext('2d'),p={x:5,y:5},v={x:1,y:0},food={x:15,y:10},tail=[];window.onkeydown=e=>{if(e.key==='Escape'){clearInterval(window.gameTimer);window.onkeydown=null;nav('library')}if(e.key==='ArrowUp')v={x:0,y:-1};if(e.key==='ArrowDown')v={x:0,y:1};if(e.key==='ArrowLeft')v={x:-1,y:0};if(e.key==='ArrowRight')v={x:1,y:0}};window.gameTimer=setInterval(()=>{p.x=(p.x+v.x+30)%30;p.y=(p.y+v.y+18)%18;tail.push({...p});if(tail.length>8)tail.shift();if(p.x===food.x&&p.y===food.y){food={x:Math.floor(Math.random()*30),y:Math.floor(Math.random()*18)};for(let i=0;i<3;i++)tail.unshift({...p})}x.fillStyle='#050812';x.fillRect(0,0,600,360);x.fillStyle='#50e5ff';tail.forEach(q=>x.fillRect(q.x*20+2,q.y*20+2,16,16));x.fillStyle='#c05cff';x.fillRect(food.x*20+2,food.y*20+2,16,16)},100)}
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&currentTab!=='home')nav('home');let order=['home','library','store','social','settings'];if(e.key==='ArrowRight'||e.key==='ArrowLeft'){let i=order.indexOf(currentTab);i=(i+(e.key==='ArrowRight'?1:-1)+order.length)%order.length;nav(order[i])}});
(async()=>{if(localStorage.horizonSetup==='1'&&localStorage.horizonSession){try{let s=JSON.parse(localStorage.horizonSession);currentUser=s.user;render()}catch{setup()}}else setup()})();
